package exception.dao;

public class AlreadyExistDataMapperException extends DataMapperException{

    public AlreadyExistDataMapperException(String message, Throwable cause) {
        super(message, cause);
    }
}
